apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spotify-stats-chart.fullname" . }}-secrets
type: Opaque
data:
  SPOTIFY_API_TOKEN: "{{ .Values.spotifyStatsSettings.spotifyAPIToken | default "" | b64enc }}"
